// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

func deepEqualsPigeonGenerated(_ lhs: Any?, _ rhs: Any?) -> Bool {
  let cleanLhs = nilOrValue(lhs) as Any?
  let cleanRhs = nilOrValue(rhs) as Any?
  switch (cleanLhs, cleanRhs) {
  case (nil, nil):
    return true

  case (nil, _), (_, nil):
    return false

  case is (Void, Void):
    return true

  case let (cleanLhsHashable, cleanRhsHashable) as (AnyHashable, AnyHashable):
    return cleanLhsHashable == cleanRhsHashable

  case let (cleanLhsArray, cleanRhsArray) as ([Any?], [Any?]):
    guard cleanLhsArray.count == cleanRhsArray.count else { return false }
    for (index, element) in cleanLhsArray.enumerated() {
      if !deepEqualsPigeonGenerated(element, cleanRhsArray[index]) {
        return false
      }
    }
    return true

  case let (cleanLhsDictionary, cleanRhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
    guard cleanLhsDictionary.count == cleanRhsDictionary.count else { return false }
    for (key, cleanLhsValue) in cleanLhsDictionary {
      guard cleanRhsDictionary.index(forKey: key) != nil else { return false }
      if !deepEqualsPigeonGenerated(cleanLhsValue, cleanRhsDictionary[key]!) {
        return false
      }
    }
    return true

  default:
    // Any other type shouldn't be able to be used with pigeon. File an issue if you find this to be untrue.
    return false
  }
}

func deepHashPigeonGenerated(value: Any?, hasher: inout Hasher) {
  if let valueList = value as? [AnyHashable] {
     for item in valueList { deepHashPigeonGenerated(value: item, hasher: &hasher) }
     return
  }

  if let valueDict = value as? [AnyHashable: AnyHashable] {
    for key in valueDict.keys { 
      hasher.combine(key)
      deepHashPigeonGenerated(value: valueDict[key]!, hasher: &hasher)
    }
    return
  }

  if let hashableValue = value as? AnyHashable {
    hasher.combine(hashableValue.hashValue)
  }

  return hasher.combine(String(describing: value))
}

    

enum FBStandardEvent: Int {
  case adClick = 0
  case adImpression = 1
  case completedRegistration = 2
  case completedTutorial = 3
  case contact = 4
  case customizeProduct = 5
  case donate = 6
  case findLocation = 7
  case rated = 8
  case schedule = 9
  case searched = 10
  case startTrial = 11
  case submitApplication = 12
  case subscribe = 13
  case viewedContent = 14
  case addedPaymentInfo = 15
  case addedToCart = 16
  case addedToWishlist = 17
  case initiatedCheckout = 18
  case purchased = 19
  case achievedLevel = 20
  case unlockedAchievement = 21
  case spentCredits = 22
}

enum FBStandardParameter: Int {
  case parameterNameContent = 0
  case parameterNameContentID = 1
  case parameterNameContentType = 2
  case parameterNameCurrency = 3
  case parameterNameDescription = 4
  case parameterNameLevel = 5
  case parameterNameMaxRatingValue = 6
  case parameterNameNumItems = 7
  case parameterNamePaymentInfoAvailable = 8
  case parameterNameRegistrationMethod = 9
  case parameterNameSearchString = 10
  case parameterNameSuccess = 11
  case parameterNameAdType = 12
  case parameterNameOrderID = 13
  case parameterNameEventName = 14
  case parameterNameLogTime = 15
}

enum FBUserDataType: Int {
  case email = 0
  case firstName = 1
  case lastName = 2
  case phone = 3
  case dateOfBirth = 4
  case gender = 5
  case city = 6
  case state = 7
  case zip = 8
  case country = 9
  case externalId = 10
}

/// Generated class from Pigeon that represents data sent in messages.
struct FBLogEventRequest: Hashable {
  var eventName: String
  var eventParameters: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FBLogEventRequest? {
    let eventName = pigeonVar_list[0] as! String
    let eventParameters = pigeonVar_list[1] as! [String: String]

    return FBLogEventRequest(
      eventName: eventName,
      eventParameters: eventParameters
    )
  }
  func toList() -> [Any?] {
    return [
      eventName,
      eventParameters,
    ]
  }
  static func == (lhs: FBLogEventRequest, rhs: FBLogEventRequest) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FBLogPurchaseRequest: Hashable {
  var amount: Double
  var currency: String
  var eventParameter: [String: String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FBLogPurchaseRequest? {
    let amount = pigeonVar_list[0] as! Double
    let currency = pigeonVar_list[1] as! String
    let eventParameter = pigeonVar_list[2] as! [String: String]

    return FBLogPurchaseRequest(
      amount: amount,
      currency: currency,
      eventParameter: eventParameter
    )
  }
  func toList() -> [Any?] {
    return [
      amount,
      currency,
      eventParameter,
    ]
  }
  static func == (lhs: FBLogPurchaseRequest, rhs: FBLogPurchaseRequest) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FBStandardEventParameter: Hashable {
  var parameterName: FBStandardParameter
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FBStandardEventParameter? {
    let parameterName = pigeonVar_list[0] as! FBStandardParameter
    let value = pigeonVar_list[1] as! String

    return FBStandardEventParameter(
      parameterName: parameterName,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      parameterName,
      value,
    ]
  }
  static func == (lhs: FBStandardEventParameter, rhs: FBStandardEventParameter) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FBLogStandardEventRequest: Hashable {
  var eventName: FBStandardEvent
  var parameters: [FBStandardEventParameter]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FBLogStandardEventRequest? {
    let eventName = pigeonVar_list[0] as! FBStandardEvent
    let parameters = pigeonVar_list[1] as! [FBStandardEventParameter]

    return FBLogStandardEventRequest(
      eventName: eventName,
      parameters: parameters
    )
  }
  func toList() -> [Any?] {
    return [
      eventName,
      parameters,
    ]
  }
  static func == (lhs: FBLogStandardEventRequest, rhs: FBLogStandardEventRequest) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FBSetUserDataRequest: Hashable {
  var type: FBUserDataType
  var value: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FBSetUserDataRequest? {
    let type = pigeonVar_list[0] as! FBUserDataType
    let value = pigeonVar_list[1] as! String

    return FBSetUserDataRequest(
      type: type,
      value: value
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      value,
    ]
  }
  static func == (lhs: FBSetUserDataRequest, rhs: FBSetUserDataRequest) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FBSetDataProcessingOptionsRequest: Hashable {
  var modes: [String]
  var country: Int64? = nil
  var state: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FBSetDataProcessingOptionsRequest? {
    let modes = pigeonVar_list[0] as! [String]
    let country: Int64? = nilOrValue(pigeonVar_list[1])
    let state: Int64? = nilOrValue(pigeonVar_list[2])

    return FBSetDataProcessingOptionsRequest(
      modes: modes,
      country: country,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      modes,
      country,
      state,
    ]
  }
  static func == (lhs: FBSetDataProcessingOptionsRequest, rhs: FBSetDataProcessingOptionsRequest) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FBAnonIdResponse: Hashable {
  var fbAnonId: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FBAnonIdResponse? {
    let fbAnonId = pigeonVar_list[0] as! String

    return FBAnonIdResponse(
      fbAnonId: fbAnonId
    )
  }
  func toList() -> [Any?] {
    return [
      fbAnonId
    ]
  }
  static func == (lhs: FBAnonIdResponse, rhs: FBAnonIdResponse) -> Bool {
    return deepEqualsPigeonGenerated(lhs.toList(), rhs.toList())  }
  func hash(into hasher: inout Hasher) {
    deepHashPigeonGenerated(value: toList(), hasher: &hasher)
  }
}

private class PigeonGeneratedPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FBStandardEvent(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FBStandardParameter(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return FBUserDataType(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      return FBLogEventRequest.fromList(self.readValue() as! [Any?])
    case 133:
      return FBLogPurchaseRequest.fromList(self.readValue() as! [Any?])
    case 134:
      return FBStandardEventParameter.fromList(self.readValue() as! [Any?])
    case 135:
      return FBLogStandardEventRequest.fromList(self.readValue() as! [Any?])
    case 136:
      return FBSetUserDataRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return FBSetDataProcessingOptionsRequest.fromList(self.readValue() as! [Any?])
    case 138:
      return FBAnonIdResponse.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class PigeonGeneratedPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? FBStandardEvent {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? FBStandardParameter {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? FBUserDataType {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? FBLogEventRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? FBLogPurchaseRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? FBStandardEventParameter {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? FBLogStandardEventRequest {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? FBSetUserDataRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? FBSetDataProcessingOptionsRequest {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? FBAnonIdResponse {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class PigeonGeneratedPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return PigeonGeneratedPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return PigeonGeneratedPigeonCodecWriter(data: data)
  }
}

class PigeonGeneratedPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = PigeonGeneratedPigeonCodec(readerWriter: PigeonGeneratedPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol FlutterMetaAppadsSdkHostApi {
  func initSdk(enableLogging: Bool) throws
  func setUserData(request: FBSetUserDataRequest) throws
  func logStandardEvent(request: FBLogStandardEventRequest) throws
  func logPurchase(request: FBLogPurchaseRequest) throws
  func logEvents(request: FBLogEventRequest) throws
  func getFbAnonId() throws -> FBAnonIdResponse?
  func setAdvertiserTrackingEnabled(isEnabled: Bool) throws
  func setAdvertiserIDCollectionEnabled(isEnabled: Bool) throws
  func setAutoLogAppEventsEnabled(isEnabled: Bool) throws
  func setDataProcessingOptions(request: FBSetDataProcessingOptionsRequest) throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class FlutterMetaAppadsSdkHostApiSetup {
  static var codec: FlutterStandardMessageCodec { PigeonGeneratedPigeonCodec.shared }
  /// Sets up an instance of `FlutterMetaAppadsSdkHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: FlutterMetaAppadsSdkHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let initSdkChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.initSdk\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initSdkChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enableLoggingArg = args[0] as! Bool
        do {
          try api.initSdk(enableLogging: enableLoggingArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initSdkChannel.setMessageHandler(nil)
    }
    let setUserDataChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setUserData\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setUserDataChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FBSetUserDataRequest
        do {
          try api.setUserData(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setUserDataChannel.setMessageHandler(nil)
    }
    let logStandardEventChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logStandardEvent\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logStandardEventChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FBLogStandardEventRequest
        do {
          try api.logStandardEvent(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      logStandardEventChannel.setMessageHandler(nil)
    }
    let logPurchaseChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logPurchase\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logPurchaseChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FBLogPurchaseRequest
        do {
          try api.logPurchase(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      logPurchaseChannel.setMessageHandler(nil)
    }
    let logEventsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logEvents\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      logEventsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FBLogEventRequest
        do {
          try api.logEvents(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      logEventsChannel.setMessageHandler(nil)
    }
    let getFbAnonIdChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.getFbAnonId\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getFbAnonIdChannel.setMessageHandler { _, reply in
        do {
          let result = try api.getFbAnonId()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      getFbAnonIdChannel.setMessageHandler(nil)
    }
    let setAdvertiserTrackingEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAdvertiserTrackingEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAdvertiserTrackingEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isEnabledArg = args[0] as! Bool
        do {
          try api.setAdvertiserTrackingEnabled(isEnabled: isEnabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAdvertiserTrackingEnabledChannel.setMessageHandler(nil)
    }
    let setAdvertiserIDCollectionEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAdvertiserIDCollectionEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAdvertiserIDCollectionEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isEnabledArg = args[0] as! Bool
        do {
          try api.setAdvertiserIDCollectionEnabled(isEnabled: isEnabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAdvertiserIDCollectionEnabledChannel.setMessageHandler(nil)
    }
    let setAutoLogAppEventsEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAutoLogAppEventsEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setAutoLogAppEventsEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let isEnabledArg = args[0] as! Bool
        do {
          try api.setAutoLogAppEventsEnabled(isEnabled: isEnabledArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setAutoLogAppEventsEnabledChannel.setMessageHandler(nil)
    }
    let setDataProcessingOptionsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setDataProcessingOptions\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setDataProcessingOptionsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! FBSetDataProcessingOptionsRequest
        do {
          try api.setDataProcessingOptions(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setDataProcessingOptionsChannel.setMessageHandler(nil)
    }
  }
}
