// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package cat.durban.sergio.flutter_meta_appads_sdk

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object PigeonGeneratedPigeonUtils {

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class FBStandardEvent(val raw: Int) {
  AD_CLICK(0),
  AD_IMPRESSION(1),
  COMPLETED_REGISTRATION(2),
  COMPLETED_TUTORIAL(3),
  CONTACT(4),
  CUSTOMIZE_PRODUCT(5),
  DONATE(6),
  FIND_LOCATION(7),
  RATED(8),
  SCHEDULE(9),
  SEARCHED(10),
  START_TRIAL(11),
  SUBMIT_APPLICATION(12),
  SUBSCRIBE(13),
  VIEWED_CONTENT(14),
  ADDED_PAYMENT_INFO(15),
  ADDED_TO_CART(16),
  ADDED_TO_WISHLIST(17),
  INITIATED_CHECKOUT(18),
  PURCHASED(19),
  ACHIEVED_LEVEL(20),
  UNLOCKED_ACHIEVEMENT(21),
  SPENT_CREDITS(22);

  companion object {
    fun ofRaw(raw: Int): FBStandardEvent? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class FBStandardParameter(val raw: Int) {
  PARAMETER_NAME_CONTENT(0),
  PARAMETER_NAME_CONTENT_ID(1),
  PARAMETER_NAME_CONTENT_TYPE(2),
  PARAMETER_NAME_CURRENCY(3),
  PARAMETER_NAME_DESCRIPTION(4),
  PARAMETER_NAME_LEVEL(5),
  PARAMETER_NAME_MAX_RATING_VALUE(6),
  PARAMETER_NAME_NUM_ITEMS(7),
  PARAMETER_NAME_PAYMENT_INFO_AVAILABLE(8),
  PARAMETER_NAME_REGISTRATION_METHOD(9),
  PARAMETER_NAME_SEARCH_STRING(10),
  PARAMETER_NAME_SUCCESS(11),
  PARAMETER_NAME_AD_TYPE(12),
  PARAMETER_NAME_ORDER_ID(13),
  PARAMETER_NAME_EVENT_NAME(14),
  PARAMETER_NAME_LOG_TIME(15);

  companion object {
    fun ofRaw(raw: Int): FBStandardParameter? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class FBUserDataType(val raw: Int) {
  EMAIL(0),
  FIRST_NAME(1),
  LAST_NAME(2),
  PHONE(3),
  DATE_OF_BIRTH(4),
  GENDER(5),
  CITY(6),
  STATE(7),
  ZIP(8),
  COUNTRY(9),
  EXTERNAL_ID(10);

  companion object {
    fun ofRaw(raw: Int): FBUserDataType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FBLogEventRequest (
  val eventName: String,
  val eventParameters: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FBLogEventRequest {
      val eventName = pigeonVar_list[0] as String
      val eventParameters = pigeonVar_list[1] as Map<String, String>
      return FBLogEventRequest(eventName, eventParameters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eventName,
      eventParameters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FBLogEventRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FBLogPurchaseRequest (
  val amount: Double,
  val currency: String,
  val eventParameter: Map<String, String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FBLogPurchaseRequest {
      val amount = pigeonVar_list[0] as Double
      val currency = pigeonVar_list[1] as String
      val eventParameter = pigeonVar_list[2] as Map<String, String>
      return FBLogPurchaseRequest(amount, currency, eventParameter)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      amount,
      currency,
      eventParameter,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FBLogPurchaseRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FBStandardEventParameter (
  val parameterName: FBStandardParameter,
  val value: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FBStandardEventParameter {
      val parameterName = pigeonVar_list[0] as FBStandardParameter
      val value = pigeonVar_list[1] as String
      return FBStandardEventParameter(parameterName, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      parameterName,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FBStandardEventParameter) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FBLogStandardEventRequest (
  val eventName: FBStandardEvent,
  val parameters: List<FBStandardEventParameter>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FBLogStandardEventRequest {
      val eventName = pigeonVar_list[0] as FBStandardEvent
      val parameters = pigeonVar_list[1] as List<FBStandardEventParameter>
      return FBLogStandardEventRequest(eventName, parameters)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      eventName,
      parameters,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FBLogStandardEventRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FBSetUserDataRequest (
  val type: FBUserDataType,
  val value: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FBSetUserDataRequest {
      val type = pigeonVar_list[0] as FBUserDataType
      val value = pigeonVar_list[1] as String
      return FBSetUserDataRequest(type, value)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      value,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FBSetUserDataRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FBSetDataProcessingOptionsRequest (
  val modes: List<String>,
  val country: Long? = null,
  val state: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FBSetDataProcessingOptionsRequest {
      val modes = pigeonVar_list[0] as List<String>
      val country = pigeonVar_list[1] as Long?
      val state = pigeonVar_list[2] as Long?
      return FBSetDataProcessingOptionsRequest(modes, country, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      modes,
      country,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FBSetDataProcessingOptionsRequest) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FBAnonIdResponse (
  val fbAnonId: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FBAnonIdResponse {
      val fbAnonId = pigeonVar_list[0] as String
      return FBAnonIdResponse(fbAnonId)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fbAnonId,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is FBAnonIdResponse) {
      return false
    }
    if (this === other) {
      return true
    }
    return PigeonGeneratedPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class PigeonGeneratedPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FBStandardEvent.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FBStandardParameter.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          FBUserDataType.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FBLogEventRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FBLogPurchaseRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FBStandardEventParameter.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FBLogStandardEventRequest.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FBSetUserDataRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FBSetDataProcessingOptionsRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FBAnonIdResponse.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is FBStandardEvent -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is FBStandardParameter -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is FBUserDataType -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is FBLogEventRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is FBLogPurchaseRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is FBStandardEventParameter -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is FBLogStandardEventRequest -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is FBSetUserDataRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is FBSetDataProcessingOptionsRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is FBAnonIdResponse -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface FlutterMetaAppadsSdkHostApi {
  fun initSdk(enableLogging: Boolean)
  fun setUserData(request: FBSetUserDataRequest)
  fun logStandardEvent(request: FBLogStandardEventRequest)
  fun logPurchase(request: FBLogPurchaseRequest)
  fun logEvents(request: FBLogEventRequest)
  fun getFbAnonId(): FBAnonIdResponse?
  fun setAdvertiserTrackingEnabled(isEnabled: Boolean)
  fun setAdvertiserIDCollectionEnabled(isEnabled: Boolean)
  fun setAutoLogAppEventsEnabled(isEnabled: Boolean)
  fun setDataProcessingOptions(request: FBSetDataProcessingOptionsRequest)

  companion object {
    /** The codec used by FlutterMetaAppadsSdkHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      PigeonGeneratedPigeonCodec()
    }
    /** Sets up an instance of `FlutterMetaAppadsSdkHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: FlutterMetaAppadsSdkHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.initSdk$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enableLoggingArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.initSdk(enableLoggingArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setUserData$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as FBSetUserDataRequest
            val wrapped: List<Any?> = try {
              api.setUserData(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logStandardEvent$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as FBLogStandardEventRequest
            val wrapped: List<Any?> = try {
              api.logStandardEvent(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logPurchase$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as FBLogPurchaseRequest
            val wrapped: List<Any?> = try {
              api.logPurchase(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logEvents$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as FBLogEventRequest
            val wrapped: List<Any?> = try {
              api.logEvents(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.getFbAnonId$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.getFbAnonId())
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAdvertiserTrackingEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isEnabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setAdvertiserTrackingEnabled(isEnabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAdvertiserIDCollectionEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isEnabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setAdvertiserIDCollectionEnabled(isEnabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAutoLogAppEventsEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val isEnabledArg = args[0] as Boolean
            val wrapped: List<Any?> = try {
              api.setAutoLogAppEventsEnabled(isEnabledArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setDataProcessingOptions$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as FBSetDataProcessingOptionsRequest
            val wrapped: List<Any?> = try {
              api.setDataProcessingOptions(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              PigeonGeneratedPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
