// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

bool _deepEquals(Object? a, Object? b) {
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    return a.length == b.length &&
        a.entries.every((MapEntry<Object?, Object?> entry) =>
            (b as Map<Object?, Object?>).containsKey(entry.key) &&
            _deepEquals(entry.value, b[entry.key]));
  }
  return a == b;
}

enum FBStandardEvent {
  adClick,
  adImpression,
  completedRegistration,
  completedTutorial,
  contact,
  customizeProduct,
  donate,
  findLocation,
  rated,
  schedule,
  searched,
  startTrial,
  submitApplication,
  subscribe,
  viewedContent,
  addedPaymentInfo,
  addedToCart,
  addedToWishlist,
  initiatedCheckout,
  purchased,
  achievedLevel,
  unlockedAchievement,
  spentCredits,
}

enum FBStandardParameter {
  parameterNameContent,
  parameterNameContentID,
  parameterNameContentType,
  parameterNameCurrency,
  parameterNameDescription,
  parameterNameLevel,
  parameterNameMaxRatingValue,
  parameterNameNumItems,
  parameterNamePaymentInfoAvailable,
  parameterNameRegistrationMethod,
  parameterNameSearchString,
  parameterNameSuccess,
  parameterNameAdType,
  parameterNameOrderID,
  parameterNameEventName,
  parameterNameLogTime,
}

enum FBUserDataType {
  email,
  firstName,
  lastName,
  phone,
  dateOfBirth,
  gender,
  city,
  state,
  zip,
  country,
  externalId,
}

class FBLogEventRequest {
  FBLogEventRequest({
    required this.eventName,
    required this.eventParameters,
  });

  String eventName;

  Map<String, String> eventParameters;

  List<Object?> _toList() {
    return <Object?>[
      eventName,
      eventParameters,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FBLogEventRequest decode(Object result) {
    result as List<Object?>;
    return FBLogEventRequest(
      eventName: result[0]! as String,
      eventParameters:
          (result[1] as Map<Object?, Object?>?)!.cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FBLogEventRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class FBLogPurchaseRequest {
  FBLogPurchaseRequest({
    required this.amount,
    required this.currency,
    required this.eventParameter,
  });

  double amount;

  String currency;

  Map<String, String> eventParameter;

  List<Object?> _toList() {
    return <Object?>[
      amount,
      currency,
      eventParameter,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FBLogPurchaseRequest decode(Object result) {
    result as List<Object?>;
    return FBLogPurchaseRequest(
      amount: result[0]! as double,
      currency: result[1]! as String,
      eventParameter:
          (result[2] as Map<Object?, Object?>?)!.cast<String, String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FBLogPurchaseRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class FBStandardEventParameter {
  FBStandardEventParameter({
    required this.parameterName,
    required this.value,
  });

  FBStandardParameter parameterName;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      parameterName,
      value,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FBStandardEventParameter decode(Object result) {
    result as List<Object?>;
    return FBStandardEventParameter(
      parameterName: result[0]! as FBStandardParameter,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FBStandardEventParameter ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class FBLogStandardEventRequest {
  FBLogStandardEventRequest({
    required this.eventName,
    required this.parameters,
  });

  FBStandardEvent eventName;

  List<FBStandardEventParameter> parameters;

  List<Object?> _toList() {
    return <Object?>[
      eventName,
      parameters,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FBLogStandardEventRequest decode(Object result) {
    result as List<Object?>;
    return FBLogStandardEventRequest(
      eventName: result[0]! as FBStandardEvent,
      parameters:
          (result[1] as List<Object?>?)!.cast<FBStandardEventParameter>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FBLogStandardEventRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class FBSetUserDataRequest {
  FBSetUserDataRequest({
    required this.type,
    required this.value,
  });

  FBUserDataType type;

  String value;

  List<Object?> _toList() {
    return <Object?>[
      type,
      value,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FBSetUserDataRequest decode(Object result) {
    result as List<Object?>;
    return FBSetUserDataRequest(
      type: result[0]! as FBUserDataType,
      value: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FBSetUserDataRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class FBSetDataProcessingOptionsRequest {
  FBSetDataProcessingOptionsRequest({
    required this.modes,
    this.country,
    this.state,
  });

  List<String> modes;

  int? country;

  int? state;

  List<Object?> _toList() {
    return <Object?>[
      modes,
      country,
      state,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FBSetDataProcessingOptionsRequest decode(Object result) {
    result as List<Object?>;
    return FBSetDataProcessingOptionsRequest(
      modes: (result[0] as List<Object?>?)!.cast<String>(),
      country: result[1] as int?,
      state: result[2] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FBSetDataProcessingOptionsRequest ||
        other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class FBAnonIdResponse {
  FBAnonIdResponse({
    required this.fbAnonId,
  });

  String fbAnonId;

  List<Object?> _toList() {
    return <Object?>[
      fbAnonId,
    ];
  }

  Object encode() {
    return _toList();
  }

  static FBAnonIdResponse decode(Object result) {
    result as List<Object?>;
    return FBAnonIdResponse(
      fbAnonId: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FBAnonIdResponse || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(encode(), other.encode());
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => Object.hashAll(_toList());
}

class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    } else if (value is FBStandardEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    } else if (value is FBStandardParameter) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    } else if (value is FBUserDataType) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    } else if (value is FBLogEventRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is FBLogPurchaseRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is FBStandardEventParameter) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is FBLogStandardEventRequest) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is FBSetUserDataRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is FBSetDataProcessingOptionsRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is FBAnonIdResponse) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : FBStandardEvent.values[value];
      case 130:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : FBStandardParameter.values[value];
      case 131:
        final int? value = readValue(buffer) as int?;
        return value == null ? null : FBUserDataType.values[value];
      case 132:
        return FBLogEventRequest.decode(readValue(buffer)!);
      case 133:
        return FBLogPurchaseRequest.decode(readValue(buffer)!);
      case 134:
        return FBStandardEventParameter.decode(readValue(buffer)!);
      case 135:
        return FBLogStandardEventRequest.decode(readValue(buffer)!);
      case 136:
        return FBSetUserDataRequest.decode(readValue(buffer)!);
      case 137:
        return FBSetDataProcessingOptionsRequest.decode(readValue(buffer)!);
      case 138:
        return FBAnonIdResponse.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class FlutterMetaAppadsSdkHostApi {
  /// Constructor for [FlutterMetaAppadsSdkHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  FlutterMetaAppadsSdkHostApi(
      {BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix =
            messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<void> initSdk(bool enableLogging) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.initSdk$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[enableLogging]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setUserData(FBSetUserDataRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setUserData$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> logStandardEvent(FBLogStandardEventRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logStandardEvent$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> logPurchase(FBLogPurchaseRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logPurchase$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> logEvents(FBLogEventRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.logEvents$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<FBAnonIdResponse?> getFbAnonId() async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.getFbAnonId$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return (pigeonVar_replyList[0] as FBAnonIdResponse?);
    }
  }

  Future<void> setAdvertiserTrackingEnabled(bool isEnabled) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAdvertiserTrackingEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[isEnabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setAdvertiserIDCollectionEnabled(bool isEnabled) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAdvertiserIDCollectionEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[isEnabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setAutoLogAppEventsEnabled(bool isEnabled) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setAutoLogAppEventsEnabled$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[isEnabled]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> setDataProcessingOptions(
      FBSetDataProcessingOptionsRequest request) async {
    final String pigeonVar_channelName =
        'dev.flutter.pigeon.flutter_meta_appads_sdk.FlutterMetaAppadsSdkHostApi.setDataProcessingOptions$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel =
        BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture =
        pigeonVar_channel.send(<Object?>[request]);
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_sendFuture as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}
